### ISSUE TITLE
Failed to contact the origin

### ISSUE THREAD

**Issue by pesterhazy** [confetti-clj/confetti#28] opened 2016-08-01 08:37 UTC
After setting up a site automatically, when I visit the cloudfront url, I get the error message

```
ERROR

Failed to contact the origin.
```

Looking at the CloudFront settings, it looks like the S3 bucket is configured as a custom backend. To fix it I set it up to use the S3 bucket directly (you can select the S3 bucket you want from a list when creating an origin). The origin type is "S3 origin".

**Comment by martinklepsch** [comment] 2016-08-01 09:37
Could you add the options you were using to this issue so I can try to
reproduce?

I believe the reason to use a custom endpoint is that when you serve static
sites (instead of just files) you need `/ -> index.html` mapping which only
the S3 website endpoint supports.

And to use the website endpoint you need a custom origin.

**Comment by pesterhazy** [comment] 2016-08-08 17:43
It was basically the same as described in this issue https://github.com/confetti-clj/confetti/issues/27 -- the only unusual thing is that I used an apex domain.

**Comment by martinklepsch** [comment] 2016-11-26 09:48
There's not enough info here for me to do anything useful, closing.

**Closed by martinklepsch** 2016-11-26 09:48 UTC
